name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "-"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Platform
      description: Selection of team zone.
      options:
        - label: Frontend
          required: false
        - label: Backend
          required: false
        - label: Mobile
          required: false

  - type: dropdown
    id: Browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: Mobile
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Android
        - IOS
        - Flutter
        - Native
